---
apiVersion: v1
kind: ServiceAccount
  labels:
    app.kubernetes.io/name: kuberay-operator
    app.kubernetes.io/instance: kuberay-lab
    app.kubernetes.io/part-of: kuberay
  name: kuberay-operator
