apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kuberay-operator
    app.kubernetes.io/instance: kuberay-ray
    app.kubernetes.io/part-of: kuberay
  name: kuberay-operator
  namespace: kuberay-operator
